server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: dotnet-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: dotnet-app
          level: ""
          __path__: /logs/*.txt   # caminho dentro do container Promtail
